import { useState } from "react";

function Skills({addSkillValue, skills, setSkills}) {
  const possibleSkills = [
    "Communication",
    "Leadership",
    "Teamwork",
    "Problem Solving",
    "Time Management",
    "Adaptability",
    "Critical Thinking",
    "Project Management",
    "Customer Service",
    "Data Analysis",
    "Negotiation",
    "Presentation Skills",
    "Technical Writing",
    "Sales",
    "Marketing",
    "Budgeting",
    "Conflict Resolution",
    "Creativity",
    "Research",
    "Attention to Detail",
    "Strategic Planning",
    "Networking",
    "Coaching",
    "Decision Making",
    "Public Speaking",
    "Organizational Skills",
    "Risk Management",
    "Multitasking",
    "Collaboration",
    "Analytical Thinking",
    "Emotional Intelligence",
    "Programming",
    "Database Management",
    "Event Planning",
    "SEO",
    "Content Creation",
    "Copywriting",
    "Editing",
    "Graphic Design",
    "UX/UI Design",
    "Video Production",
    "Social Media Management",
    "Agile Methodologies",
    "Scrum",
    "Kanban",
    "Software Development",
    "Web Development",
    "Cybersecurity",
    "Cloud Computing",
    "Machine Learning",
    "Artificial Intelligence",
    "Blockchain",
    "Cryptocurrency",
    "Data Science",
    "DevOps",
    "Networking (IT)",
    "Systems Administration",
    "Quality Assurance",
    "IT Support",
    "Hardware Troubleshooting",
    "Ethical Hacking",
    "Penetration Testing",
    "Automation",
    "Virtualization",
    "Linux Administration",
    "Windows Administration",
    "Python",
    "JavaScript",
    "Java",
    "C#",
    "C++",
    "SQL",
    "NoSQL",
    "HTML/CSS",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Django",
    "Flask",
    "Ruby on Rails",
    "PHP",
    "Perl",
    "Swift",
    "Kotlin",
    "Objective-C",
    "Go",
    "Rust",
    "MATLAB",
    "R",
    "SAS",
    "SPSS",
    "Stata",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Scikit-Learn",
    "Hadoop",
    "Spark",
    "Hive",
    "Pig",
    "AWS",
    "Azure",
    "Google Cloud",
    "Docker",
    "Kubernetes",
    "Jenkins",
    "Ansible",
    "Terraform",
    "Chef",
    "Puppet",
    "Elasticsearch",
    "Kafka",
    "Redis",
    "MongoDB",
    "Cassandra",
    "PostgreSQL",
    "MySQL",
    "MariaDB",
    "Oracle",
    "Microsoft SQL Server",
    "Salesforce",
    "HubSpot",
    "Marketo",
    "Pardot",
    "Mailchimp",
    "Constant Contact",
    "Google Analytics",
    "Tableau",
    "Power BI",
    "QlikView",
    "Looker",
    "Excel",
    "Microsoft Word",
    "Microsoft PowerPoint",
    "Microsoft Access",
    "Microsoft Outlook",
    "Google Sheets",
    "Google Docs",
    "Google Slides",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe InDesign",
    "Adobe Premiere Pro",
    "Adobe After Effects",
    "Final Cut Pro",
    "iMovie",
    "Audacity",
    "GarageBand",
    "Pro Tools",
    "Ableton Live",
    "FL Studio",
    "Logic Pro",
    "Customer Relationship Management (CRM)",
    "Enterprise Resource Planning (ERP)",
    "Human Resource Information System (HRIS)",
    "Learning Management System (LMS)",
    "Point of Sale (POS)",
    "Supply Chain Management (SCM)",
    "Accounting Software",
    "Tax Preparation",
    "Financial Analysis",
    "Investment Management",
    "Wealth Management",
    "Risk Assessment",
    "Internal Audit",
    "Compliance",
    "Corporate Finance",
    "Forensic Accounting",
    "Mergers and Acquisitions",
    "Real Estate",
    "Insurance",
    "Credit Analysis",
    "Fraud Prevention",
    "Econometrics",
    "Statistics",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "Geology",
    "Environmental Science",
    "Astronomy",
    "Mechanical Engineering",
    "Electrical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Biomedical Engineering",
    "Aerospace Engineering",
    "Robotics",
    "Mechatronics",
    "Nanotechnology",
    "Renewable Energy",
    "Sustainable Design",
    "Construction Management",
    "Interior Design",
    "Urban Planning",
    "Architecture",
    "AutoCAD",
    "Revit",
    "SketchUp",
    "3ds Max",
    "Blender",
    "Unity",
    "Unreal Engine",
    "Game Development",
    "Game Design",
    "Sound Design",
    "Voice Acting",
    "Copy Editing",
    "Proofreading",
    "Translation",
    "Interpretation",
    "Transcription",
    "Subtitling",
    "Sign Language",
    "Foreign Languages",
    "ESL Teaching",
    "TESOL",
    "TEFL",
    "TOEFL",
    "IELTS",
    "Cambridge English",
    "Creative Writing",
    "Journalism",
    "Blogging",
    "Podcasting",
    "Broadcasting",
    "Photography",
    "Photo Editing",
    "Videography",
    "Film Production",
    "Sound Engineering",
    "Lighting Design",
    "Stage Management",
    "Theater Production",
    "Dance",
    "Choreography",
    "Music Theory",
    "Instrumental Performance",
    "Vocal Performance",
    "Composition",
    "Conducting",
    "Music Production",
    "Music Education",
    "Art History",
    "Curating",
    "Museum Management",
    "Restoration",
    "Conservation",
    "Graphic Novels",
    "Comic Book Art",
    "Calligraphy",
    "Illustration",
    "Animation",
    "Storyboarding",
    "3D Modeling",
    "Textile Design",
    "Fashion Design",
    "Pattern Making",
    "Sewing",
    "Merchandising",
    "Retail Management",
    "Supply Chain Optimization",
    "Inventory Management",
    "Procurement",
    "Logistics",
    "Warehousing",
    "Freight Forwarding",
    "Customs Brokerage",
    "Import/Export Compliance",
    "International Trade",
    "E-commerce",
    "Digital Marketing",
    "Affiliate Marketing",
    "Pay-Per-Click (PPC)",
    "Search Engine Marketing (SEM)",
    "Influencer Marketing",
    "Content Marketing",
    "Email Marketing",
    "Mobile Marketing",
    "Video Marketing",
    "Brand Management",
    "Product Management",
    "Category Management",
    "Pricing Strategy",
    "Market Research",
    "Consumer Behavior",
    "Business Analysis",
    "Business Development",
    "Strategic Partnerships",
    "Account Management",
    "Key Account Management",
    "Customer Retention",
    "Customer Success",
    "Customer Experience",
    "User Experience (UX)",
    "User Interface (UI)",
    "Product Design",
    "Service Design",
    "Design Thinking",
    "Human-Centered Design",
    "Lean Startup",
    "Lean Manufacturing",
    "Six Sigma",
    "Kaizen",
    "Total Quality Management (TQM)",
    "ISO Standards",
    "Safety Management",
    "Incident Management",
    "Crisis Management",
    "Disaster Recovery",
    "Business Continuity",
    "Emergency Management",
    "Security Management",
    "Facilities Management",
    "Real Estate Management",
    "Property Management",
    "Event Management",
    "Hospitality Management",
    "Tourism Management",
    "Culinary Arts",
    "Food Safety",
    "Nutrition",
    "Dietetics",
    "Personal Training",
    "Fitness Instruction",
    "Sports Coaching",
    "Sports Medicine",
    "Physical Therapy",
    "Occupational Therapy",
    "Speech Therapy",
    "Counseling",
    "Psychotherapy",
    "Clinical Psychology",
    "Child Psychology",
    "Forensic Psychology",
    "Social Work",
    "Community Outreach",
    "Case Management",
    "Fundraising",
    "Grant Writing",
    "Nonprofit Management",
    "Volunteer Management",
    "Philanthropy",
    "Corporate Social Responsibility (CSR)",
    "Diversity and Inclusion",
    "Equality and Equity",
    "Human Resources",
    "Recruiting",
    "Talent Acquisition",
    "Onboarding",
    "Employee Relations",
    "Performance Management",
    "Compensation and Benefits",
    "Labor Law",
    "Workplace Safety",
    "Industrial Relations",
    "Organizational Development",
    "Change Management",
    "Learning and Development",
    "Training",
    "Coaching and Mentoring",
    "Career Counseling",
    "Executive Coaching",
    "Life Coaching",
    "Health Coaching",
    "Wellness Coaching",
    "Financial Planning",
    "Retirement Planning",
    "Estate Planning",
    "Tax Planning",
    "Insurance Planning",
    "Real Estate Investment",
    "Stock Trading",
    "Options Trading",
    "Futures Trading",
    "Cryptocurrency Trading",
    "Foreign Exchange (Forex) Trading",
    "Commodities Trading",
    "Portfolio Management",
    "Wealth Management",
    "Risk Management",
    "Compliance Management",
    "Governance",
    "Internal Controls",
    "Auditing",
    "Forensic Accounting",
    "Fraud Examination",
    "Ethics and Compliance",
    "Legal Research",
    "Legal Writing",
    "Paralegal Studies",
    "Contract Law",
    "Corporate Law",
    "Intellectual Property Law",
    "Labor Law",
    "Employment Law",
    "Family Law",
    "Criminal Law",
    "Civil Litigation",
    "Mediation",
    "Arbitration",
    "Dispute Resolution",
    "Regulatory Affairs",
    "Government Relations",
    "Public Policy",
    "Advocacy",
    "Lobbying",
    "Political Campaigning",
    "Community Organizing",
    "Social Advocacy",
    "Environmental Advocacy",
    "Human Rights Advocacy",
    "Economic Development",
    "Urban Development",
    "Rural Development",
    "Sustainable Development",
    "International Development",
    "Public Health",
    "Epidemiology",
    "Biostatistics",
    "Health Policy",
    "Health Administration",
    "Healthcare Management",
    "Healthcare Compliance",
    "Medical Coding",
    "Medical Billing",
    "Health Information Management",
    "Medical Records Management",
    "Clinical Research",
    "Clinical Trials",
    "Pharmaceutical Research",
    "Drug Development",
    "Biotechnology",
    "Genomics",
    "Proteomics",
    "Bioinformatics",
    "Biomedical Research",
    "Medical Device Design",
    "Medical Device Regulation",
    "Pharmacovigilance",
    "Regulatory Affairs",
    "Quality Assurance (QA)",
    "Quality Control (QC)",
    "Good Manufacturing Practice (GMP)",
    "Good Laboratory Practice (GLP)",
    "Good Clinical Practice (GCP)",
    "Lean Six Sigma",
    "Operational Excellence",
    "Process Improvement",
    "Continuous Improvement",
    "Root Cause Analysis",
    "Failure Mode and Effects Analysis (FMEA)",
    "Corrective and Preventive Actions (CAPA)",
    "Operational Risk Management",
    "Financial Risk Management",
    "Credit Risk Management",
    "Market Risk Management",
    "Operational Resilience",
    "Supply Chain Risk Management",
    "Cyber Risk Management",
    "Information Security Management",
    "Data Privacy",
    "Data Protection",
    "Compliance Risk Management",
    "Regulatory Compliance",
    "Third-Party Risk Management",
    "Vendor Management",
    "Procurement Risk Management",
    "Contract Management",
    "Intellectual Property Management",
    "Patent Law",
    "Trademark Law",
    "Copyright Law",
    "Trade Secrets Law",
    "Licensing Agreements",
    "Technology Transfer",
    "Joint Ventures",
    "Strategic Alliances",
    "Franchise Management",
    "Entrepreneurship",
    "Startup Management",
    "Venture Capital",
    "Private Equity",
    "Angel Investing",
    "Crowdfunding",
    "Small Business Management",
    "Franchise Management",
    "Retail Operations",
    "Store Management",
    "Visual Merchandising",
    "Loss Prevention",
    "Customer Loyalty Programs",
    "Customer Feedback",
    "Mystery Shopping",
    "Brand Loyalty",
    "Brand Advocacy",
    "Customer Insights",
    "Customer Journey Mapping",
    "Customer Segmentation",
    "Market Segmentation",
    "Competitor Analysis",
    "Product Launch",
    "Product Roadmap",
    "Go-to-Market Strategy",
    "Channel Strategy",
    "Sales Strategy",
    "Sales Forecasting",
    "Sales Operations",
    "Sales Enablement",
    "Sales Training",
    "Sales Coaching",
    "Inside Sales",
    "Field Sales",
    "Direct Sales",
    "Indirect Sales",
    "Channel Sales",
    "E-commerce Sales",
    "Retail Sales",
    "B2B Sales",
    "B2C Sales",
    "Enterprise Sales",
    "Solution Selling",
    "Consultative Selling",
    "Relationship Selling",
    "Transactional Selling",
    "Cross-Selling",
    "Up-Selling",
    "Customer Prospecting",
    "Lead Generation",
    "Lead Nurturing",
    "Lead Scoring",
    "Lead Qualification",
    "Account-Based Marketing",
    "Content Marketing",
    "Digital Advertising",
    "Traditional Advertising",
    "Media Planning",
    "Media Buying",
    "Public Relations",
    "Press Releases",
    "Crisis Communications",
    "Corporate Communications",
    "Internal Communications",
    "External Communications",
    "Social Media Strategy",
    "Social Media Advertising",
    "Influencer Outreach",
    "Community Management",
    "Online Community Building",
    "Content Calendar Management",
    "Content Strategy",
    "Editorial Strategy",
    "Content Syndication",
    "Video Content Strategy",
    "Interactive Content Strategy",
    "User-Generated Content Strategy",
    "Content Curation",
    "Content Distribution",
    "Content Amplification",
    "Content Personalization",
    "A/B Testing",
    "Conversion Rate Optimization (CRO)",
    "Growth Hacking",
    "Viral Marketing",
    "Referral Marketing",
    "Account Management",
    "Customer Relationship Management",
    "Client Services",
    "Client Success",
    "Partner Management",
    "Channel Partner Management",
    "Alliance Management",
    "Distribution Management",
    "Supplier Management",
    "Procurement Strategy",
    "Supply Chain Strategy",
    "Logistics Strategy",
    "Transportation Management",
    "Freight Management",
    "Shipping and Receiving",
    "Customs Compliance",
    "Trade Compliance",
    "Import/Export Regulations",
    "Tariffs and Duties",
    "International Shipping",
    "Global Trade",
    "Foreign Trade Zones",
    "Free Trade Agreements",
    "Supply Chain Optimization",
    "Supply Chain Resilience",
    "Supply Chain Visibility",
    "Supply Chain Collaboration",
    "Supply Chain Risk Management",
    "Supply Chain Sustainability",
    "Supply Chain Security",
    "Supply Chain Automation",
    "Supply Chain Analytics",
    "Supply Chain Software",
    "Inventory Optimization",
    "Inventory Planning",
    "Inventory Control",
    "Inventory Accuracy",
    "Cycle Counting",
    "Demand Planning",
    "Demand Forecasting",
    "Supply Planning",
    "Production Planning",
    "Materials Planning",
    "Capacity Planning",
    "Sales and Operations Planning (S&OP)",
    "Integrated Business Planning (IBP)",
    "Demand-Driven MRP",
    "Lean Manufacturing",
    "Just-in-Time (JIT)",
    "Total Productive Maintenance (TPM)",
    "Kanban",
    "5S",
    "Value Stream Mapping",
    "SMED",
    "Kaizen",
    "Poka-Yoke",
    "Heijunka",
    "Jidoka",
    "Gemba",
    "Hoshin Kanri",
    "TPM",
    "OEE",
    "KPI Management",
    "Balanced Scorecard",
    "Business Process Management (BPM)",
    "Business Process Reengineering (BPR)",
    "Workflow Automation",
    "Robotic Process Automation (RPA)",
    "Digital Transformation",
    "Artificial Intelligence (AI)",
    "Machine Learning (ML)",
    "Natural Language Processing (NLP)",
    "Computer Vision",
    "Speech Recognition",
    "Chatbots",
    "Virtual Assistants",
    "Predictive Analytics",
    "Prescriptive Analytics",
    "Big Data Analytics",
    "Data Mining",
    "Data Wrangling",
    "Data Visualization",
    "Data Storytelling",
    "Data Governance",
    "Data Quality",
    "Data Security",
    "Data Architecture",
    "Data Modeling",
    "Data Integration",
    "ETL (Extract, Transform, Load)",
    "Data Warehousing",
    "Data Lakes",
    "Data Fabric",
    "Data Mesh",
    "DataOps",
    "MLOps",
    "AIOps",
    "DevOps",
    "Continuous Integration (CI)",
    "Continuous Delivery (CD)",
    "Infrastructure as Code (IaC)",
    "Configuration Management",
    "Serverless Computing",
    "Microservices Architecture",
    "Event-Driven Architecture",
    "API Management",
    "API Development",
    "API Integration",
    "API Documentation",
    "API Testing",
    "RESTful APIs",
    "GraphQL",
    "gRPC",
    "Webhooks",
    "MQTT",
    "WebSockets",
    "SOAP",
    "OData",
    "OpenAPI",
    "Swagger",
    "Postman",
    "Fiddler",
    "Burp Suite",
    "Wireshark",
    "Nmap",
    "Metasploit",
    "Nessus",
    "OpenVAS",
    "OWASP",
    "CISSP",
    "CEH",
    "CISM",
    "CISA",
    "Security+",
    "Penetration Testing",
    "Red Teaming",
    "Blue Teaming",
    "Purple Teaming",
    "Incident Response",
    "Threat Intelligence",
    "Threat Hunting",
    "Digital Forensics",
    "Malware Analysis",
    "Reverse Engineering",
    "Cyber Threat Analysis",
    "Cyber Threat Intelligence",
    "Cyber Risk Management",
    "Cyber Security Operations",
    "Security Operations Center (SOC)",
    "Network Security",
    "Endpoint Security",
    "Cloud Security",
    "Application Security",
    "Data Security",
    "Identity and Access Management (IAM)",
    "Privileged Access Management (PAM)",
    "Multi-Factor Authentication (MFA)",
    "Single Sign-On (SSO)",
    "Zero Trust Security",
    "Security Awareness Training",
    "Security Policy Development",
    "Security Compliance",
    "Security Auditing",
    "Security Risk Assessment",
    "Security Posture Management",
    "Vulnerability Management",
    "Patch Management",
    "Encryption",
    "Cryptography",
    "Public Key Infrastructure (PKI)",
    "SSL/TLS",
    "Firewall Management",
    "Intrusion Detection Systems (IDS)",
    "Intrusion Prevention Systems (IPS)",
    "Anti-Malware",
    "Anti-Phishing",
    "Anti-Spam",
    "Email Security",
    "Web Security",
    "Content Filtering",
    "SIEM (Security Information and Event Management)",
    "SOAR (Security Orchestration, Automation, and Response)",
    "Threat Intelligence Platforms (TIP)",
    "Network Monitoring",
    "Network Traffic Analysis",
    "Network Forensics",
    "Network Troubleshooting",
    "Network Design",
    "Network Architecture",
    "Network Administration",
    "Network Management",
    "Network Automation",
    "Network Virtualization",
    "Software-Defined Networking (SDN)",
    "Network Function Virtualization (NFV)",
    "Cloud Networking",
    "Hybrid Cloud",
    "Multi-Cloud",
    "Private Cloud",
    "Public Cloud",
    "Edge Computing",
    "Fog Computing",
    "Mobile Computing",
    "Wearable Computing",
    "Internet of Things (IoT)",
    "Industrial IoT",
    "Smart Cities",
    "Smart Homes",
    "Smart Grid",
    "Smart Agriculture",
    "Smart Manufacturing",
    "Smart Retail",
    "Smart Healthcare",
    "Digital Twins",
    "3D Printing",
    "Additive Manufacturing",
    "CNC Machining",
    "Robotics Process Automation (RPA)",
    "Cobots",
    "Drones",
    "Autonomous Vehicles",
    "Connected Vehicles",
    "Telematics",
    "Fleet Management",
    "Supply Chain Automation",
    "Warehouse Automation",
    "Retail Automation",
    "Healthcare Automation",
    "Finance Automation",
    "Legal Automation",
    "Human Resources Automation",
    "Customer Service Automation",
    "Sales Automation",
    "Marketing Automation",
    "DevOps Automation",
    "IT Automation",
    "Data Center Automation",
    "Network Automation",
    "Cloud Automation",
    "Application Automation",
    "Business Process Automation (BPA)",
    "Robotic Desktop Automation (RDA)",
    "Digital Workforce",
    "Virtual Agents",
    "Conversational AI",
    "Voice Assistants",
    "Chatbots",
    "Natural Language Understanding (NLU)",
    "Natural Language Generation (NLG)",
    "Text Analytics",
    "Sentiment Analysis",
    "Topic Modeling",
    "Machine Translation",
    "Optical Character Recognition (OCR)",
    "Augmented Reality (AR)",
    "Virtual Reality (VR)",
    "Mixed Reality (MR)",
    "Extended Reality (XR)",
    "Spatial Computing",
    "Holography",
    "Volumetric Video",
    "360-Degree Video",
    "Immersive Experiences",
    "Digital Marketing",
    "Email Marketing",
    "Social Media Marketing",
    "Content Marketing",
    "Influencer Marketing",
    "Video Marketing",
    "SEO (Search Engine Optimization)",
    "SEM (Search Engine Marketing)",
    "PPC (Pay-Per-Click)",
    "Affiliate Marketing",
    "Referral Marketing",
    "Account-Based Marketing",
    "Event Marketing",
    "Field Marketing",
    "Trade Show Marketing",
    "Exhibition Marketing",
    "Experiential Marketing",
    "Brand Marketing",
    "Product Marketing",
    "Channel Marketing",
    "Retail Marketing",
    "E-commerce Marketing",
    "Direct Marketing",
    "Database Marketing",
    "Customer Journey Mapping",
    "Customer Persona Development",
    "Customer Segmentation",
    "Customer Retention",
    "Customer Acquisition",
    "Customer Loyalty Programs",
    "Customer Advocacy",
    "Customer Feedback Management",
    "Customer Experience Management",
    "Customer Relationship Management (CRM)",
    "Customer Data Platforms (CDP)",
    "Customer Success Management",
    "Client Success Management",
    "Account Management",
    "Key Account Management",
    "Strategic Account Management",
    "Partnership Management",
    "Channel Partner Management",
    "Reseller Management",
    "Distributor Management",
    "Supplier Relationship Management (SRM)",
    "Vendor Management",
    "Procurement Management",
    "Contract Management",
    "Supplier Diversity",
    "Supplier Development",
    "Supplier Auditing",
    "Supplier Quality Management",
    "Supplier Risk Management",
    "Supplier Performance Management",
    "Supply Chain Risk Management",
    "Supply Chain Resilience",
    "Supply Chain Agility",
    "Supply Chain Optimization",
    "Supply Chain Digitization",
    "Supply Chain Transparency",
    "Supply Chain Collaboration",
    "Supply Chain Visibility",
    "Supply Chain Analytics",
    "Supply Chain Management Software",
    "Inventory Management Software",
    "Warehouse Management Software",
    "Transportation Management Software",
    "Freight Management Software",
    "Logistics Management Software",
    "Fleet Management Software",
    "Route Optimization Software",
    "Demand Planning Software",
    "Sales and Operations Planning (S&OP) Software",
    "Integrated Business Planning (IBP) Software",
    "Procurement Software",
    "Supplier Management Software",
    "Contract Management Software",
    "Supply Chain Automation Software",
    "Supply Chain AI",
    "Supply Chain Machine Learning",
    "Supply Chain Data Science",
    "Supply Chain Predictive Analytics",
    "Supply Chain Prescriptive Analytics",
    "Supply Chain Blockchain",
    "Supply Chain Internet of Things (IoT)",
    "Supply Chain Augmented Reality (AR)",
    "Supply Chain Virtual Reality (VR)",
    "Supply Chain Robotics",
    "Supply Chain Drones",
    "Supply Chain Autonomous Vehicles",
    "Supply Chain 3D Printing",
    "Supply Chain Additive Manufacturing",
    "Supply Chain CNC Machining",
    "Supply Chain AI-Powered Automation",
    "Supply Chain Machine Vision",
    "Supply Chain Smart Sensors",
    "Supply Chain Digital Twins",
    "Supply Chain Real-Time Monitoring",
    "Supply Chain Cybersecurity",
    "Supply Chain Risk Assessment",
    "Supply Chain Risk Mitigation",
    "Supply Chain Disruption Management",
    "Supply Chain Contingency Planning",
    "Supply Chain Crisis Management",
    "Supply Chain Emergency Response",
    "Supply Chain Recovery Planning",
    "Supply Chain Resilience Planning",
    "Supply Chain Sustainability Planning",
    "Supply Chain Environmental Impact Assessment",
    "Supply Chain Carbon Footprint Reduction",
    "Supply Chain Circular Economy",
    "Supply Chain Zero Waste",
    "Supply Chain Green Logistics",
    "Supply Chain Green Transportation",
    "Supply Chain Green Procurement",
    "Supply Chain Green Manufacturing",
    "Supply Chain Green Packaging",
    "Supply Chain Green Warehousing",
    "Supply Chain Green Buildings",
    "Supply Chain Renewable Energy",
    "Supply Chain Energy Efficiency",
    "Supply Chain Water Efficiency",
    "Supply Chain Waste Management",
    "Supply Chain Recycling",
    "Supply Chain Hazardous Materials Management",
    "Supply Chain Regulatory Compliance",
    "Supply Chain Legal Compliance",
    "Supply Chain Ethical Compliance",
    "Supply Chain Social Compliance",
    "Supply Chain Human Rights Compliance",
    "Supply Chain Labor Rights Compliance",
    "Supply Chain Anti-Corruption Compliance",
    "Supply Chain Anti-Bribery Compliance",
    "Supply Chain Anti-Money Laundering Compliance",
    "Supply Chain Export Control Compliance",
    "Supply Chain Import Control Compliance",
    "Supply Chain Trade Compliance",
    "Supply Chain Sanctions Compliance",
    "Supply Chain Customs Compliance",
    "Supply Chain Tariff Compliance",
    "Supply Chain Duty Compliance",
    "Supply Chain Quota Compliance",
    "Supply Chain Export Licensing",
    "Supply Chain Import Licensing",
    "Supply Chain Export Documentation",
    "Supply Chain Import Documentation",
    "Supply Chain Trade Finance",
    "Supply Chain Export Financing",
    "Supply Chain Import Financing",
    "Supply Chain Letter of Credit",
    "Supply Chain Documentary Collection",
    "Supply Chain Open Account",
    "Supply Chain Advance Payment",
    "Supply Chain Consignment",
    "Supply Chain Payment Terms",
    "Supply Chain Incoterms",
    "Supply Chain Freight Forwarding",
    "Supply Chain Customs Brokerage",
    "Supply Chain Cargo Insurance",
    "Supply Chain Marine Insurance",
    "Supply Chain Air Cargo Insurance",
    "Supply Chain Land Cargo Insurance",
    "Supply Chain Multimodal Transport Insurance",
    "Supply Chain Liability Insurance",
    "Supply Chain Property Insurance",
    "Supply Chain Business Interruption Insurance",
    "Supply Chain Cyber Insurance",
    "Supply Chain Crime Insurance",
    "Supply Chain Professional Indemnity Insurance",
    "Supply Chain Product Liability Insurance",
    "Supply Chain Product Recall Insurance",
    "Supply Chain Employers' Liability Insurance",
    "Supply Chain Public Liability Insurance",
    "Supply Chain Environmental Liability Insurance",
    "Supply Chain Directors' and Officers' Liability Insurance",
    "Supply Chain Trade Credit Insurance",
    "Supply Chain Political Risk Insurance",
    "Supply Chain Kidnap and Ransom Insurance",
    "Supply Chain Terrorism Insurance",
    "Supply Chain War Insurance",
    "Supply Chain Reinsurance",
    "Supply Chain Captive Insurance",
    "Supply Chain Self-Insurance",
    "Supply Chain Risk Retention",
    "Supply Chain Risk Transfer",
    "Supply Chain Risk Sharing",
    "Supply Chain Risk Financing",
    "Supply Chain Risk Modeling",
    "Supply Chain Risk Simulation",
    "Supply Chain Risk Quantification",
    "Supply Chain Risk Appetite",
    "Supply Chain Risk Tolerance",
    "Supply Chain Risk Culture",
    "Supply Chain Risk Governance",
    "Supply Chain Risk Policy",
    "Supply Chain Risk Strategy",
    "Supply Chain Risk Framework",
    "Supply Chain Risk Process",
    "Supply Chain Risk Identification",
    "Supply Chain Risk Analysis",
    "Supply Chain Risk Evaluation",
    "Supply Chain Risk Treatment",
    "Supply Chain Risk Monitoring",
    "Supply Chain Risk Reporting",
    "Supply Chain Risk Communication",
    "Supply Chain Risk Training",
    "Supply Chain Risk Awareness",
    "Supply Chain Risk Knowledge Management",
    "Supply Chain Risk Knowledge Sharing",
    "Supply Chain Risk Benchmarking",
    "Supply Chain Risk Best Practices",
    "Supply Chain Risk Standards",
    "Supply Chain Risk Certification",
    "Supply Chain Risk Auditing",
    "Supply Chain Risk Assurance",
    "Supply Chain Risk Advisory",
    "Supply Chain Risk Consulting",
    "Supply Chain Risk Outsourcing",
    "Supply Chain Risk Insourcing",
    "Supply Chain Risk Offshoring",
    "Supply Chain Risk Nearshoring",
    "Supply Chain Risk Onshoring",
    "Supply Chain Risk Reshoring",
    "Supply Chain Risk Sourcing",
    "Supply Chain Risk Procurement",
    "Supply Chain Risk Contracting",
    "Supply Chain Risk Negotiation",
    "Supply Chain Risk Mediation",
    "Supply Chain Risk Arbitration",
    "Supply Chain Risk Litigation",
    "Supply Chain Risk Settlement",
    "Supply Chain Risk Compensation",
    "Supply Chain Risk Indemnity",
    "Supply Chain Risk Insurance",
    "Supply Chain Risk Reinsurance",
    "Supply Chain Risk Hedging",
    "Supply Chain Risk Derivatives",
    "Supply Chain Risk Options",
    "Supply Chain Risk Futures",
    "Supply Chain Risk Swaps",
    "Supply Chain Risk Forwards",
    "Supply Chain Risk Structured Finance",
    "Supply Chain Risk Securitization",
    "Supply Chain Risk Syndication",
    "Supply Chain Risk Leveraged Finance",
    "Supply Chain Risk Project Finance",
    "Supply Chain Risk Asset Finance",
    "Supply Chain Risk Equipment Finance",
    "Supply Chain Risk Trade Finance",
    "Supply Chain Risk Export Finance",
    "Supply Chain Risk Import Finance",
    "Supply Chain Risk Commodity Finance",
    "Supply Chain Risk Corporate Finance",
    "Supply Chain Risk Investment Banking",
    "Supply Chain Risk Private Banking",
    "Supply Chain Risk Wealth Management",
    "Supply Chain Risk Family Office",
    "Supply Chain Risk Estate Planning",
    "Supply Chain Risk Tax Planning",
    "Supply Chain Risk Retirement Planning",
    "Supply Chain Risk Philanthropy",
    "Supply Chain Risk Charitable Giving",
    "Supply Chain Risk Impact Investing",
    "Supply Chain Risk Socially Responsible Investing",
    "Supply Chain Risk Environmental, Social, and Governance (ESG) Investing",
    "Supply Chain Risk Green Investing",
    "Supply Chain Risk Sustainable Investing",
    "Supply Chain Risk Ethical Investing",
    "Supply Chain Risk Faith-Based Investing",
    "Supply Chain Risk Islamic Finance",
    "Supply Chain Risk Shariah Compliance",
    "Supply Chain Risk Halal Certification",
    "Supply Chain Risk Kosher Certification",
    "Supply Chain Risk Vegan Certification",
    "Supply Chain Risk Organic Certification",
    "Supply Chain Risk Fair Trade Certification",
    "Supply Chain Risk Rainforest Alliance Certification",
    "Supply Chain Risk UTZ Certification",
    "Supply Chain Risk FSC Certification",
    "Supply Chain Risk PEFC Certification",
    "Supply Chain Risk ISO Certification",
    "Supply Chain Risk LEED Certification",
    "Supply Chain Risk BREEAM Certification",
    "Supply Chain Risk WELL Certification",
    "Supply Chain Risk Fitwel Certification",
    "Supply Chain Risk RESET Certification",
    "Supply Chain Risk SITES Certification",
    "Supply Chain Risk Envision Certification",
    "Supply Chain Risk Green Globe Certification",
    "Supply Chain Risk EarthCheck Certification",
    "Supply Chain Risk Travelife Certification",
    "Supply Chain Risk Green Key Certification",
    "Supply Chain Risk Green Seal Certification",
    "Supply Chain Risk Energy Star Certification",
    "Supply Chain Risk WaterSense Certification",
    "Supply Chain Risk EPEAT Certification",
    "Supply Chain Risk Cradle to Cradle Certification",
    "Supply Chain Risk Fairmined Certification",
    "Supply Chain Risk Fairtrade Gold Certification",
    "Supply Chain Risk Conflict-Free Gold Certification",
    "Supply Chain Risk Recycled Gold Certification",
    "Supply Chain Risk Recycled Silver Certification",
    "Supply Chain Risk Recycled Platinum Certification",
    "Supply Chain Risk Recycled Palladium Certification",
    "Supply Chain Risk Recycled Rhodium Certification",
    "Supply Chain Risk Recycled Copper Certification",
    "Supply Chain Risk Recycled Aluminum Certification",
    "Supply Chain Risk Recycled Steel Certification",
    "Supply Chain Risk Recycled Glass Certification",
    "Supply Chain Risk Recycled Plastic Certification",
    "Supply Chain Risk Recycled Paper Certification",
    "Supply Chain Risk Recycled Cardboard Certification",
    "Supply Chain Risk Recycled Textile Certification",
    "Supply Chain Risk Recycled Leather Certification",
    "Supply Chain Risk Recycled Wood Certification",
    "Supply Chain Risk Recycled Rubber Certification",
    "Supply Chain Risk Recycled Ceramic Certification",
    "Supply Chain Risk Recycled Concrete Certification",
    "Supply Chain Risk Recycled Asphalt Certification",
    "Supply Chain Risk Recycled Aggregate Certification",
    "Supply Chain Risk Recycled Bitumen Certification",
    "Supply Chain Risk Recycled Fiberglass Certification",
    "Supply Chain Risk Recycled Insulation Certification",
    "Supply Chain Risk Recycled Metal Certification",
    "Supply Chain Risk Recycled Paperboard Certification",
    "Supply Chain Risk Recycled Packaging Certification",
    "Supply Chain Risk Recycled Pallet Certification",
    "Supply Chain Risk Recycled Crate Certification",
    "Supply Chain Risk Recycled Container Certification",
    "Supply Chain Risk Recycled Drum Certification",
    "Supply Chain Risk Recycled Barrel Certification",
    "Supply Chain Risk Recycled Tote Certification",
    "Supply Chain Risk Recycled Bag Certification",
    "Supply Chain Risk Recycled Pouch Certification",
    "Supply Chain Risk Recycled Bottle Certification",
    "Supply Chain Risk Recycled Jar Certification",
    "Supply Chain Risk Recycled Can Certification",
    "Supply Chain Risk Recycled Tray Certification",
    "Supply Chain Risk Recycled Lid Certification",
    "Supply Chain Risk Recycled Cap Certification",
    "Supply Chain Risk Recycled Closure Certification",
    "Supply Chain Risk Recycled Label Certification",
    "Supply Chain Risk Recycled Sticker Certification",
    "Supply Chain Risk Recycled Tape Certification",
    "Supply Chain Risk Recycled Twine Certification",
    "Supply Chain Risk Recycled Rope Certification",
    "Supply Chain Risk Recycled Net Certification",
    "Supply Chain Risk Recycled Mesh Certification",
    "Supply Chain Risk Recycled Fabric Certification",
    "Supply Chain Risk Recycled Yarn Certification",
    "Supply Chain Risk Recycled Thread Certification",
    "Supply Chain Risk Recycled Fiber Certification",
    "Supply Chain Risk Recycled Fleece Certification",
    "Supply Chain Risk Recycled Felt Certification",
    "Supply Chain Risk Recycled Velvet Certification",
    "Supply Chain Risk Recycled Wool Certification",
    "Supply Chain Risk Recycled Cotton Certification",
    "Supply Chain Risk Recycled Silk Certification",
    "Supply Chain Risk Recycled Linen Certification",
    "Supply Chain Risk Recycled Hemp Certification",
    "Supply Chain Risk Recycled Jute Certification",
    "Supply Chain Risk Recycled Bamboo Certification",
    "Supply Chain Risk Recycled Rattan Certification",
    "Supply Chain Risk Recycled Cane Certification",
    "Supply Chain Risk Recycled Seagrass Certification",
    "Supply Chain Risk Recycled Coconut Certification",
    "Supply Chain Risk Recycled Cork Certification",
    "Supply Chain Risk Recycled Shell Certification",
    "Supply Chain Risk Recycled Bone Certification",
    "Supply Chain Risk Recycled Horn Certification",
    "Supply Chain Risk Recycled Antler Certification",
    "Supply Chain Risk Recycled Feather Certification",
    "Supply Chain Risk Recycled Fur Certification",
    "Supply Chain Risk Recycled Leather Certification",
    "Supply Chain Risk Recycled Hide Certification",
    "Supply Chain Risk Recycled Wool Certification",
    "Supply Chain Risk Recycled Fleece Certification",
    "Supply Chain Risk Recycled Felt Certification",
    "Supply Chain Risk Recycled Velvet Certification",
    "Supply Chain Risk Recycled Silk Certification",
    "Supply Chain Risk Recycled Linen Certification",
    "Supply Chain Risk Recycled Hemp Certification",
    "Supply Chain Risk Recycled Jute Certification",
    "Supply Chain Risk Recycled Bamboo Certification",
    "Supply Chain Risk Recycled Rattan Certification",
    "Supply Chain Risk Recycled Cane Certification",
    "Supply Chain Risk Recycled Seagrass Certification",
    "Supply Chain Risk Recycled Coconut Certification",
    "Supply Chain Risk Recycled Cork Certification",
    "Supply Chain Risk Recycled Shell Certification",
    "Supply Chain Risk Recycled Bone Certification",
    "Supply Chain Risk Recycled Horn Certification",
    "Supply Chain Risk Recycled Antler Certification",
    "Supply Chain Risk Recycled Feather Certification",
    "Supply Chain Risk Recycled Fur Certification",
    "Supply Chain Risk Recycled Leather Certification",
    "Supply Chain Risk Recycled Hide Certification",
    "Supply Chain Risk Recycled Wool Certification",
    "Supply Chain Risk Recycled Fleece Certification",
    "Supply Chain Risk Recycled Felt Certification",
    "Supply Chain Risk Recycled Velvet Certification",
    "Supply Chain Risk Recycled Silk Certification",
    "Supply Chain Risk Recycled Linen Certification",
    "Supply Chain Risk Recycled Hemp Certification",
    "Supply Chain Risk Recycled Jute Certification",
    "Supply Chain Risk Recycled Bamboo Certification",
    "Supply Chain Risk Recycled Rattan Certification",
    "Supply Chain Risk Recycled Cane Certification",
    "Supply Chain Risk Recycled Seagrass Certification",
    "Supply Chain Risk Recycled Coconut Certification",
    "Supply Chain Risk Recycled Cork Certification",
    "Supply Chain Risk Recycled Shell Certification",
    "Supply Chain Risk Recycled Bone Certification",
    "Supply Chain Risk Recycled Horn Certification",
    "Supply Chain Risk Recycled Antler Certification",
    "Supply Chain Risk Recycled Feather Certification",
    "Supply Chain Risk Recycled Fur Certification",
    "Supply Chain Risk Recycled Leather Certification",
    "Supply Chain Risk Recycled Hide Certification",
    "Supply Chain Risk Recycled Wool Certification",
    "Supply Chain Risk Recycled Fleece Certification",
    "Supply Chain Risk Recycled Felt Certification",
    "Supply Chain Risk Recycled Velvet Certification",
    "Supply Chain Risk Recycled Silk Certification",
    "Supply Chain Risk Recycled Linen Certification",
    "Supply Chain Risk Recycled Hemp Certification",
    "Supply Chain Risk Recycled Jute Certification",
    "Supply Chain Risk Recycled Bamboo Certification",
    "Supply Chain Risk Recycled Rattan Certification",
    "Supply Chain Risk Recycled Cane Certification",
    "Supply Chain Risk Recycled Seagrass Certification",
    "Supply Chain Risk Recycled Coconut Certification",
    "Supply Chain Risk Recycled Cork Certification",
    "Supply Chain Risk Recycled Shell Certification",
    "Supply Chain Risk Recycled Bone Certification",
    "Supply Chain Risk Recycled Horn Certification",
    "Supply Chain Risk Recycled Antler Certification",
    "Supply Chain Risk Recycled Feather Certification",
    "Supply Chain Risk Recycled Fur Certification",
    "Supply Chain Risk Recycled Leather Certification",
    "Supply Chain Risk Recycled Hide Certification",
    "Supply Chain Risk Recycled Wool Certification",
    "Supply Chain Risk Recycled Fleece Certification",
    "Supply Chain Risk Recycled Felt Certification",
    "Supply Chain Risk Recycled Velvet Certification",
    "Supply Chain Risk Recycled Silk Certification",
    "Supply Chain Risk Recycled Linen Certification",
    "Supply Chain Risk Recycled Hemp Certification",
    "Supply Chain Risk Recycled Jute Certification",
    "Supply Chain Risk Recycled Bamboo Certification",
    "Supply Chain Risk Recycled Rattan Certification",
    "Supply Chain Risk Recycled Cane Certification",
    "Supply Chain Risk Recycled Seagrass Certification",
    "Supply Chain Risk Recycled Coconut Certification",
    "Supply Chain Risk Recycled Cork Certification",
    "Supply Chain Risk Recycled Shell Certification",
    "Supply Chain Risk Recycled Bone Certification",
    "Supply Chain Risk Recycled Horn Certification",
    "Supply Chain Risk Recycled Antler Certification",
    "Supply Chain Risk Recycled Feather Certification",
    "Supply Chain Risk Recycled Fur Certification",
    "Supply Chain Risk Recycled Leather Certification",
    "Supply Chain Risk Recycled Hide Certification",
    "Supply Chain Risk Recycled Wool Certification",
    "Supply Chain Risk Recycled Fleece Certification",
    "Supply Chain Risk Recycled Felt Certification",
    "Supply Chain Risk Recycled Velvet Certification",
    "Supply Chain Risk Recycled Silk Certification",
    "Supply Chain Risk Recycled Linen Certification",
    "Supply Chain Risk Recycled Hemp Certification",
    "Supply Chain Risk Recycled Jute Certification",
    "Supply Chain Risk Recycled Bamboo Certification",
    "Supply Chain Risk Recycled Rattan Certification",
    "Supply Chain Risk Recycled Cane Certification",
    "Supply Chain Risk Recycled Seagrass Certification",
    "Supply Chain Risk Recycled Coconut Certification",
    "Supply Chain Risk Recycled Cork Certification",
    "Supply Chain Risk Recycled Shell Certification",
    "Supply Chain Risk Recycled Bone Certification",
    "Supply Chain Risk Recycled Horn Certification",
    "Supply Chain Risk Recycled Antler Certification",
    "Supply Chain Risk Recycled Feather Certification",
    "Supply Chain Risk Recycled Fur Certification",
    "Supply Chain Risk Recycled Leather Certification",
    "Supply Chain Risk Recycled Hide Certification",
    "Supply Chain Risk Recycled Wool Certification",
    "Supply Chain Risk Recycled Fleece Certification",
    "Supply Chain Risk Recycled Felt Certification",
    "Supply Chain Risk Recycled Velvet Certification",
    "Supply Chain Risk Recycled Silk Certification",
    "Supply Chain Risk Recycled Linen Certification",
    "Supply Chain Risk Recycled Hemp Certification",
    "Supply Chain Risk Recycled Jute Certification",
    "Supply Chain Risk Recycled Bamboo Certification",
    "Supply Chain Risk Recycled Rattan Certification",
    "Supply Chain Risk Recycled Cane Certification",
    "Supply Chain Risk Recycled Seagrass Certification",
    "Supply Chain Risk Recycled Coconut Certification",
    "Supply Chain Risk Recycled Cork Certification",
    "Supply Chain Risk Recycled Shell Certification",
    "Supply Chain Risk Recycled Bone Certification",
    "Supply Chain Risk Recycled Horn Certification",
    "Supply Chain Risk Recycled Antler Certification",
    "Supply Chain Risk Recycled Feather Certification",
    "Supply Chain Risk Recycled Fur Certification",
    "Supply Chain Risk Recycled Leather Certification",
    "Supply Chain Risk Recycled Hide Certification",
    "Supply Chain Risk Recycled Wool Certification",
    "Supply Chain Risk Recycled Fleece Certification",
    "Supply Chain Risk Recycled Felt Certification",
    "Supply Chain Risk Recycled Velvet Certification",
    "Supply Chain Risk Recycled Silk Certification",
    "Supply Chain Risk Recycled Linen Certification",
    "Supply Chain Risk Recycled Hemp Certification",
    "Supply Chain Risk Recycled Jute Certification",
    "Supply Chain Risk Recycled Bamboo Certification",
    "Supply Chain Risk Recycled Rattan Certification",
    "Supply Chain Risk Recycled Cane Certification",
    "Supply Chain Risk Recycled Seagrass Certification",
    "Supply Chain Risk Recycled Coconut Certification",
    "Supply Chain Risk Recycled Cork Certification",
    "Supply Chain Risk Recycled Shell Certification",
    "Supply Chain Risk Recycled Bone Certification",
    "Supply Chain Risk Recycled Horn Certification",
    "Supply Chain Risk Recycled Antler Certification",
    "Supply Chain Risk Recycled Feather Certification",
    "Supply Chain Risk Recycled Fur Certification",
    "Supply Chain Risk Recycled Leather Certification",
    "Supply Chain Risk Recycled Hide Certification",
    "Supply Chain Risk Recycled Wool Certification",
    "Supply Chain Risk Recycled Fleece Certification",
    "Supply Chain Risk Recycled Felt Certification",
    "Supply Chain Risk Recycled Velvet Certification",
    "Supply Chain Risk Recycled Silk Certification",
    "Supply Chain Risk Recycled Linen Certification",
    "Supply Chain Risk Recycled Hemp Certification",
    "Supply Chain Risk Recycled Jute Certification",
    "Supply Chain Risk Recycled Bamboo Certification",
    "Supply Chain Risk Recycled Rattan Certification",
    "Supply Chain Risk Recycled Cane Certification",
    "Supply Chain Risk Recycled Seagrass Certification",
    "Supply Chain Risk Recycled Coconut Certification",
    "Supply Chain Risk Recycled Cork Certification",
    "Supply Chain Risk Recycled Shell Certification",
    "Supply Chain Risk Recycled Bone Certification",
    "Supply Chain Risk Recycled Horn Certification",
    "Supply Chain Risk Recycled Antler Certification",
    "Supply Chain Risk Recycled Feather Certification",
    "Supply Chain Risk Recycled Fur Certification",
    "Supply Chain Risk Recycled Leather Certification",
    "Supply Chain Risk Recycled Hide Certification",
    "Supply Chain Risk Recycled Wool Certification",
    "Supply Chain Risk Recycled Fleece Certification",
    "Supply Chain Risk Recycled Felt Certification",
    "Supply Chain Risk Recycled Velvet Certification",
    "Supply Chain Risk Recycled Silk Certification",
    "Supply Chain Risk Recycled Linen Certification",
    "Supply Chain Risk Recycled Hemp Certification",
  ];

  // State to manage the list of skills (with text and slider values)


  // Function to handle changes in text input
  const handleTextChange = (index, event) => {
    const newSkills = [...skills];
    newSkills[index].text = event.target.value;
    setSkills(newSkills);
  };

  // Function to handle changes in range slider
  const handleRangeChange = (index, event) => {
    const newSkills = [...skills];
    newSkills[index].range = Number(event.target.value);
    setSkills(newSkills);
  };

  return (
    <>
      <div id="skills">
        {/* Render each skill with text input and slider */}
        {skills.map((skill, index) => (
          <div key={index} style={{ marginBottom: "30px" }}>
            <input
              type="text"
              value={skill.text}
              onChange={(e) => handleTextChange(index, e)}
              placeholder="Skill name"
            />
            <br />
            <input
              type="range"
              min="0"
              max="5"
              step="0.001"
              value={skill.range}
              onChange={(e) => handleRangeChange(index, e)}
            />
            <br />
            <span>{skill.range}/5</span> {/* Display current range value */}
            <br />
          </div>
        ))}
      </div>

      <button
        type="button"
        onClick={() => {
          addSkillValue(
            possibleSkills[
              parseInt(Math.random() * 1000) % (possibleSkills.length - 1)
            ],
            Math.random() * 5
          );
        }}
      >
        I'm feeling lucky
      </button>
      <br />
      <br />
      <button
        style={{ marginBottom: "30px" }}
        type="button"
        onClick={addSkillValue}
      >
        Add Skill
      </button>
      <br />
    </>
  );
}

export default Skills;
